#!/usr/bin/env python

'''
Shred blank hard drive.

If you want to remove the files and there are too many for rm, use
$ find . -name "*" -print0 | xargs -0 rm
'''

#from pprint import pprint
import time
import numpy as np

i = 0
i_max = 500
#i_max = np.inf
#n = 200000000 # default => ~1.5 Gb / file
n = 2000000

while n > 32 and i < i_max:

    t = time.time();
    x = np.random.random((n, 1))
    print '\ni = %g, n= %g' % (i, n)
    #print 'n =', n
    filename = 'n' + str(n) + '-i' + str(i) + '-t' + str(t)

    try:
        np.save(filename, x[0:n]) # Appends .npy if not already there.
        print 'Wrote file', filename
        i += 1
        # Check data written properly.
        #print '\nx ='; print x[0:n]
        #y = np.load(filename)
        #print '\ny ='; print y
    except:
        print 'exception'
        n /= 2

