#!/usr/bin/env python

'''Find recursively all files with a certain extension, say .foo, in the current
directory tree, and rename with the extension .bar (replacing .foo).

Command-line usage:
$ change_all_file_extensions .foo .bar

TODO: Use argparse to add command line flags for
  interactive mode
  dry run
  verbose
'''

# Standard
import sys
import os
import shutil
# import re
#from pprint import pprint
import time
# start_time = time.time()
# . . .
# print 'Elapsed time =', time.time() - start_time, 's'


def main():

    start_time = time.time()

    extension_old = sys.argv[1]
    extension_old_length = len(extension_old)
    extension_new = sys.argv[2]
    verbose = False

    # Find files
    for dirpath, dirnames, filenames in os.walk('.'):
        for filename in filenames:
            if extension_old_length <= len(filename) and \
                   filename[-extension_old_length:] == extension_old:
                filename_with_path = os.path.join(dirpath, filename)
                filename_new = filename[:-extension_old_length] + extension_new
                filename_with_path_new = os.path.join(dirpath, filename_new)
                if verbose:
                    print '\nRenaming ' + filename_with_path + ' to ' + filename_with_path_new
                shutil.move(filename_with_path, filename_with_path_new)

    print '\nElapsed time =', time.time() - start_time, 's'


if __name__ == "__main__":
    main()
