#!/bin/sh

# For command-line emacs invocation on Mac OS X.
# Copy this file into /usr/bin

#/Applications/Aquamacs.app/Contents/MacOS/Aquamacs "$@" # or whatever your path is
/Applications/Emacs.app/Contents/MacOS/Emacs "$@" # or whatever your path is
